version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=${PORT}
    depends_on:
      - mongo
    networks:
      - appnet

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - appnet

volumes:
  mongo_data:

networks:
  appnet:
